name: Deploy AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Configure AWS_ACCESS_KEY_ID  # 👈 EXACT environment name from GitHub

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies and package Lambda
        working-directory: lambda/cost_report
        run: |
          pip install -r requirements.txt -t .
          zip -r lambda_deploy.zip .

      - name: Deploy Lambda function
        env:
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ vars.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
        run: |
          aws lambda update-function-code \
            --function-name cost_report_function \
            --zip-file fileb://lambda_deploy.zip \
            --region "$AWS_REGION"

      - name: Notify Slack
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            STATUS="✅ Deployment succeeded"
          else
            STATUS="❌ Deployment failed"
          fi

          curl -X POST -H 'Content-type: application/json' \
            --data "{\"text\":\"$STATUS for *cost_report_function*\"}" \
            ${{ vars.SLACK_WEBHOOK_URL }}